spring:
  application:
    name: eurekaserver

server:
  port: 8761

# Configuracao para o Eureka nao se registrar sozinho.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
